### ISSUE TITLE
Starting zookeeper ... FAILED TO START

### ISSUE THREAD

**Issue by ming2377** [itsaur/zookeeper-docker-swarm#2] opened 2018-09-26 03:00 UTC
Hi,

Thanks a lot for the great image.

However, I found some issues during scale up/down # of replicas.

1. scale-up works every time, but scale-down and then scale-up will see new replicas failed to start.

It gets:
"**No quorum of new config is connected and up-to-date with the leader of last commmitted config - try invoking reconfiguration after new servers are connected and synced**"
when:
_zkServer-initialize.sh --force --myid=$ZOO_MY_ID
zkServer.sh start
zkCli.sh -server $ZOO_SERVER:2181 reconfig -add "server.$ZOO_MY_ID=$ZOO_MY_IP:2888:3888;$ZOO_PORT"
zkServer.sh stop_

It seems the new replica cannot _reconfig -add_ itself, when leader still has config that contains server.n for removed replicas. The new replica will eventually fail to start: "**java.lang.RuntimeException: My id 184 not in the peer list**" because it didn't successfully run _reconfig -add_ itself.

2.  Always sees **Starting zookeeper ... FAILED TO START** when followings are run:

_zkServer-initialize.sh --force --myid=$ZOO_MY_ID
zkServer.sh start
zkCli.sh -server $ZOO_SERVER:2181 reconfig -add "server.$ZOO_MY_ID=$ZOO_MY_IP:2888:3888;$ZOO_PORT"
zkServer.sh stop_

Although I have also seen followings, even with **Starting zookeeper ... FAILED TO START**. So scale-up somehow works.
**Committed new configuration:
server.153=10.0.4.154:2888:3888:participant;0.0.0.0:2181
server.154=10.0.4.155:2888:3888:participant;0.0.0.0:2181
server.10=10.0.4.11:2888:3888:participant;0.0.0.0:2181
server.11=10.0.4.12:2888:3888:participant;0.0.0.0:2181
server.12=10.0.4.13:2888:3888:participant;0.0.0.0:2181
version=100000006
ZooKeeper JMX enabled by default
Using config: /conf/zoo.cfg
Stopping zookeeper ... STOPPED**

**Comment by schaliasos** [comment] 2018-09-26 05:59
Hi @ming2377 ,

thanks for your detailed feedback. We will look into it.

**Comment by schaliasos** [comment] 2018-10-15 10:11
Hi @ming2377 ,

your issues were caused by invalid re-configuration of the cluster. We refactored the way we handle re-configuration in case of scale up/down or failed containers. Now, only the Leader of the cluster is responsible to reconfigure it, while before every new container was trying to do the job.

**Comment by ming2377** [comment] 2018-10-15 23:03
Thanks very much for the refactoring. Your contribution is huge and highly appreciated.

I pulled latest from master branch and "docker build" an image to test-out.
Although, I am able to scale up replicas, say from 3 to 5, but replica 4 and replica 5 are both not joining the cluster.
I found that leader container /var/log has logs contain the same error.
```
Node is leader.
Getting and saving /zookeeper/config to /usr/local/bin/configuration.
server.32=10.0.1.33:2888:3888:participant;0.0.0.0:2181
server.30=10.0.1.31:2888:3888:participant;0.0.0.0:2181
server.31=10.0.1.32:2888:3888:participant;0.0.0.0:2181
Error. Exiting.
```
replica 4 and replica 5 container /var/log has logs contain the followings.
```
Node is not a member of a cluster.
Total execution time: 0s.
```

It appears the 5 seconds cronjob running zookeeper-cleanup.sh failed on leader container. Therefore, the reconfig did not happen, thus, replica 4 and 5 are running, but not part of cluster.

I try troubleshoot a bit more, I don't see any bad usage of calculateTime that can cause the "Error. Exiting." case. So I am puzzled.

Thanks again.

**Comment by schaliasos** [comment] 2018-10-23 14:30
@ming2377 

We fixed the issue that caused the unexpected exit of the re-configuration job and also did some enhancements in the logs.

If you continue having issues please provide:

1. the docker service create command
2. the docker service scale command 
3. logs from the zookeeper leader located at /var/log

Thanks.

**Comment by schaliasos** [comment] 2018-12-19 14:44
Closing the issue at seems to be resolved.

**Closed as completed by schaliasos** 2018-12-19 14:44 UTC
